[build]
target = "armv7a-vex-v5"

[target."cfg(all(target_arch = \"arm\", target_os = \"none\"))"]
runner = "cargo v5 run --file"

[target.wasm32-unknown-unknown]
rustflags = ["-Clink-arg=--export-memory", "-Clink-arg=--import-table"]

[unstable]
build-std = ["std"]
build-std-features = ["compiler-builtins-mem"]
