[package]
name = "vexide"
version = "0.4.1"
edition = "2021"
description = "async/await powered Rust library for VEX V5 Brains"
keywords = ["Robotics", "bindings", "vex", "v5"]
categories = ["os", "api-bindings", "no-std", "science::robotics"]
license = "MIT"
repository = "https://github.com/vexide/vexide"
readme = "../../README.md"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical",
]
rust-version = "1.75.0"

[package.metadata.v5]
slot = 1
icon = "cool-x"
compress = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vexide-runtime = { workspace = true, optional = true }
vexide-devices = { workspace = true, optional = true, features = ["std"] }
vexide-graphics = { workspace = true, optional = true }
vexide-macro = { workspace = true, optional = true }

[features]
default = ["rt", "devices", "macro"]

macro = ["dep:vexide-macro", "rt", "devices"]

rt = ["dep:vexide-runtime"]
backtraces = ["rt", "vexide-runtime/backtraces"]

devices = ["dep:vexide-devices"]
dangerous_motor_tuning = ["devices", "vexide-devices/dangerous_motor_tuning"]
smart_leds_trait = ["devices", "vexide-devices/smart_leds_trait"]

graphics = ["dep:vexide-graphics"]
slint = ["vexide-graphics/slint", "graphics"]
embedded-graphics = ["vexide-graphics/embedded-graphics", "graphics"]
