[package]
name = "vexide-runtime"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Async executor and core runtime for vexide"
keywords = ["Robotics", "bindings", "vex", "v5"]
categories = ["api-bindings", "no-std", "science::robotics"]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex-sdk = { workspace = true }
no_std_io = { version = "0.6.0", features = ["alloc"] }
snafu = { workspace = true }
talc = "4.3.1"
lock_api = "0.4.11"
bitflags = "2.4.2"
futures-core = { version = "0.3.30", default-features = false, features = [
    "alloc",
] }
pin-project = "1.1.5"
replace_with = { version = "0.1.7", default-features = false }
waker-fn = "1.1.1"
async-task = "4.7.1"
compile-time = "0.2.0"

[lints]
workspace = true
